# Site settings
title: André Richter
email: andre.richter@sofi.su.se
description: > # this means to ignore newlines until "baseurl:"
   I am a PhD student in Economics at the Swedish Institute for Social Research, Stockholm University. 
   My research revolves - broadly speaking - around the inheritance of disadvantage and the role of 
   early life conditions and health. 
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://a-richter.github.io/" # the base hostname & protocol for your site
github_username:  a-richter
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
